spring:
  datasource:
    url: jdbc:mysql://rm-bp1ne2ilvesdic89lno.mysql.rds.aliyuncs.com:3306/demo?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: knight
    password: Huang19990203
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update